export const products = [
  {
    id: 1,
    name: '3D Printed Vase',
    href: '/products/1',
    price: 48,
    description: 'A beautiful and unique 3D printed vase, perfect for adding a modern touch to your home decor. This vase is available in a variety of colors and materials.',
    images: [
      { id: 1, src: '/1.jpg', alt: 'A 3D printed vase.' },
      { id: 2, src: '/2.jpg', alt: 'Side view of the vase.' },
      { id: 3, src: '/3.jpg', alt: 'Top view of the vase.' },
    ],
    category: 'Home Decor',
    material: 'PLA',
    color: 'White',
    weight: '250g',
    dimensions: '15cm x 15cm x 25cm',
    reviews: [
      { id: 1, author: 'Emily S.', rating: 5, comment: 'Absolutely stunning! The quality is amazing and it looks perfect on my mantelpiece.' },
      { id: 2, author: 'John D.', rating: 4, comment: 'Great vase, but a little smaller than I expected. Still, very happy with my purchase.' },
    ],
  },
  {
    id: 2,
    name: 'Customizable Phone Stand',
    href: '/products/2',
    price: 28,
    originalPrice: 35,
    description: 'A sleek and practical phone stand, customizable with your name or logo. This stand is perfect for your desk or nightstand and is available in a variety of colors.',
    images: [
        { id: 1, src: '/2.jpg', alt: 'A customizable phone stand.' },
    ],
    category: 'Gadgets',
    material: 'ABS',
    color: 'Black',
    weight: '150g',
    dimensions: '10cm x 8cm x 12cm',
    reviews: [
      { id: 1, author: 'Michael B.', rating: 5, comment: 'Love it! The customization is a great touch and it holds my phone perfectly.' },
    ],
  },
  {
    id: 3,
    name: 'Miniature Figurines',
    href: '/products/3',
    price: 89,
    description: 'A collection of detailed miniature figurines, perfect for tabletop gaming or as a collectible item. These figurines are available in a variety of poses and can be painted to your liking.',
    images: [
        { id: 1, src: '/3.jpg', alt: 'A collection of miniature figurines.' },
    ],
    category: 'Hobbies',
    material: 'Resin',
    color: 'Gray',
    weight: '50g',
    dimensions: '5cm x 5cm x 8cm',
    reviews: [],
  },
  {
    id: 4,
    name: 'Architectural Model',
    href: '/products/4',
    price: 225,
    originalPrice: 250,
    description: 'A detailed architectural model of a building, perfect for architects and students. This model is available in a variety of scales and can be customized to your specifications.',
    images: [
        { id: 1, src: '/1.jpg', alt: 'An architectural model of a building.' },
    ],
    category: 'Professional',
    material: 'PLA',
    color: 'White',
    weight: '1.5kg',
    dimensions: '30cm x 30cm x 20cm',
    reviews: [],
  },
  {
    id: 5,
    name: 'Custom Drone Parts',
    href: '/products/5',
    price: 120,
    description: 'A set of custom drone parts, perfect for drone enthusiasts and builders. These parts are available in a variety of materials and can be customized to your specifications.',
    images: [
        { id: 1, src: '/1.jpg', alt: 'Custom drone parts.' },
    ],
    category: 'Hobbies',
    material: 'Carbon Fiber',
    color: 'Black',
    weight: '300g',
    dimensions: 'Varies',
    reviews: [],
  },
  {
    id: 6,
    name: 'Prosthetic Hand',
    href: '/products/6',
    price: 500,
    description: 'A functional and affordable prosthetic hand, designed to be accessible to everyone. This hand is available in a variety of sizes and can be customized to your needs.',
    images: [
        { id: 1, src: '/2.jpg', alt: 'A prosthetic hand.' },
    ],
    category: 'Medical',
    material: 'PETG',
    color: 'Beige',
    weight: '500g',
    dimensions: 'Varies',
    reviews: [],
  },
  {
    id: 7,
    name: 'Lithophane Lamp',
    href: '/products/7',
    price: 50,
    originalPrice: 60,
    description: 'A personalized lithophane lamp that displays your favorite photo when lit. A perfect gift for any occasion.',
    images: [
        { id: 1, src: '/3.jpg', alt: 'A 3D printed lithophane lamp.' },
    ],
    category: 'Home Decor',
    material: 'PLA',
    color: 'White',
    weight: '300g',
    dimensions: '15cm x 15cm x 15cm',
    reviews: [],
  },
  {
    id: 8,
    name: 'Board Game Inserts',
    href: '/products/1',
    price: 45,
    description: 'Organize your favorite board games with these custom-designed inserts. Keep all your pieces in place and reduce setup time.',
    images: [
        { id: 1, src: '/1.jpg', alt: 'Custom inserts for a board game.' },
    ],
    category: 'Hobbies',
    material: 'PLA',
    color: 'Black',
    weight: '400g',
    dimensions: 'Varies',
    reviews: [],
  },
];
