export const products = [
  {
    id: 1,
    name: '3D Printed Vase',
    href: '/products/1',
    imageSrc: 'https://images.unsplash.com/photo-1593941707882-6e482a893165?q=80&w=1935&auto=format&fit=crop',
    imageAlt: 'A 3D printed vase.',
    price: '$48',
    description: 'A beautiful and unique 3D printed vase, perfect for adding a modern touch to your home decor. This vase is available in a variety of colors and materials.',
  },
  {
    id: 2,
    name: 'Customizable Phone Stand',
    href: '/products/2',
    imageSrc: 'https://images.unsplash.com/photo-1534599951508-72b6a18451b6?q=80&w=1974&auto=format&fit=crop',
    imageAlt: 'A customizable phone stand.',
    price: '$35',
    description: 'A sleek and practical phone stand, customizable with your name or logo. This stand is perfect for your desk or nightstand and is available in a variety of colors.',
  },
  {
    id: 3,
    name: 'Miniature Figurines',
    href: '/products/3',
    imageSrc: 'https://images.unsplash.com/photo-1541533810237-93e54b6f1295?q=80&w=1974&auto=format&fit=crop',
    imageAlt: 'A collection of miniature figurines.',
    price: '$89',
    description: 'A collection of detailed miniature figurines, perfect for tabletop gaming or as a collectible item. These figurines are available in a variety of poses and can be painted to your liking.',
  },
  {
    id: 4,
    name: 'Architectural Model',
    href: '/products/4',
    imageSrc: 'https://images.unsplash.com/photo-1598440947619-2c35fc93c9ad?q=80&w=1974&auto=format&fit=crop',
    imageAlt: 'An architectural model of a building.',
    price: '$250',
    description: 'A detailed architectural model of a building, perfect for architects and students. This model is available in a variety of scales and can be customized to your specifications.',
  },
  {
    id: 5,
    name: 'Custom Drone Parts',
    href: '/products/5',
    imageSrc: 'https://images.unsplash.com/photo-1507563742694-a38345e7a251?q=80&w=1974&auto=format&fit=crop',
    imageAlt: 'Custom drone parts.',
    price: '$120',
    description: 'A set of custom drone parts, perfect for drone enthusiasts and builders. These parts are available in a variety of materials and can be customized to your specifications.',
  },
  {
    id: 6,
    name: 'Prosthetic Hand',
    href: '/products/6',
    imageSrc: 'https://images.unsplash.com/photo-1599494233482-1f4a85d5b79f?q=80&w=1974&auto=format&fit=crop',
    imageAlt: 'A prosthetic hand.',
    price: '$500',
    description: 'A functional and affordable prosthetic hand, designed to be accessible to everyone. This hand is available in a variety of sizes and can be customized to your needs.',
  },
];
